local Spell = { }
Spell.__index = Spell

function Spell:GetAOETargetInfo()
end
function Spell:GetCastMethod()
end
function Spell:GetCastTime()
end
function Spell:GetCasterInnateRequirements()
end
function Spell:GetCasterInnateCosts()
end
function Spell:GetChannelData()
end
function Spell:GetClass()
end
function Spell:GetCombatMode()
end
function Spell:GetCooldownTime()
end
function Spell:GetFlavor()
end
function Spell:GetIcon()
end
function Spell:GetInstanceMaxCount()
end
function Spell:GetMaximumRange()
end
function Spell:GetMinimumRange()
end
function Spell:GetName()
end
function Spell:GetClassPower()
end
function Spell:GetPrerequisites()
end
function Spell:GetPrice()
end
function Spell:GetReagents()
end
function Spell:GetRequiredWorldZone()
end
function Spell:GetSchool()
end
function Spell:GetTargetAngle()
end
function Spell:GetTargetInnateRequirements()
end
function Spell:GetTier()
end
function Spell:IsNew()
end
function Spell:SetNewFlag(bNew)
end
function Spell:GetTradeskillRequirements()
end
function Spell.ShortcutCast()
end
function Spell.is()
end
function Spell.ShowFloater()
end
Spell.CodeEnumReagentType = {
    Item = 1,
    ItemFamily = 2,
    ItemCategory = 3
}
Spell.CodeEnumCastMethod = {
    Normal = 1,
    Channeled = 2,
    Focused = 3,
    ChanneledField = 4,
    Talent = 4,
    ClientSideInteraction = 6,
    PressHold = 1,
    RapidTap = 2,
    ChargeRelease = 3,
    Multiphase = 4,
    Transactional = 5,
    UNUSED04 = 1,
    Aura = 2
}
Spell.CodeEnumSchool = {
    Spell = 1,
    Melee = 2,
    Ranged = 3,
    Unarmed = 1
}
Spell.CodeEnumComparison = {
    Equals = 1,
    Greater = 2,
    GreaterThanEqualTo = 3,
    Less = 4,
    LessThanEqualTo = 5,
    Percent_Equals = 6,
    Percent_Greater = 7,
    Percent_GreaterThanEqualTo = 8,
    Percent_Less = 9,
    Percent_LessThanEqualTo = 10
}
Spell.CodeEnumAOESelectionType = {
    None = 1,
    Closest = 2,
    Furthest = 3,
    Random = 4,
    LowestAbsoluteHealth = 5,
    MissingMostHealth = 6
}
function Spell:GetId()
end
function Spell:GetAbilityCharges()
end
Spell.CombatMessageType = {
    General = 1,
    Experience = 2,
    QuestUpdate = 3,
    LocationChange = 4,
    Combat_Damage_Done = 5,
    Combat_Damage_Done_Critical = 6,
    Combat_Damage_Taken = 7,
    Combat_Damage_Taken_Critical = 8,
    Combat_Healing_Done = 9,
    Combat_Healing_Done_Critical = 10,
    Combat_Healing_Taken = 11,
    Combat_Healing_Taken_Critical = 12,
    Combat_Block_Taken = 13,
    Combat_Block_Done = 14,
    Combat_Parry_Taken = 15,
    Combat_Parry_Done = 16,
    Combat_Dodge_Taken = 17,
    Combat_Dodge_Done = 18,
    Combat_NoEffect_Taken = 19,
    Combat_NoEffect_Done = 20,
    Combat_Shallow_Taken = 21,
    Combat_Shallow_Done = 22,
    Combat_Falling_Damage_Done = 23,
    Combat_Death = 24,
    Error = 25,
    SpellFailure = 26,
    UNUSED00 = 27,
    UNUSED01 = 28,
    Faction = 29,
    LootBase = 30,
    LootAverage = 31,
    LootGood = 32,
    LootExcellent = 33,
    LootSuperb = 34,
    LootExquisite = 4,
    LootPhenomenal = 5,
    LootExtraordinary = 6,
    LootLegendary = 38,
    LootQuestActivation = 39,
    Achievement = 40,
    Experience_KillCreature = 41,
    Experience_ClusterBonus = 42,
    Experience_Quest = 43,
    Absorption_Taken = 44,
    Absorption_Done = 45,
    Transference_Taken = 46,
    Transference_Done = 47,
    SpellFailure_Long = 48,
    SpellFailure_Medium = 49,
    SpellFailure_Short = 50,
    SpellFailure_Target_Head = 51,
    SpellFailure_Target_Feet = 52,
    Special_Done = 53,
    Special_Taken = 54,
    UNUSED02 = 55,
    PlayerPath = 56,
    KillPerformanceReward = 57,
    MultiKillReward = 58,
    KillingSpreeReward = 59,
    LootInferior = 60,
    TelegraphEvadeReward = 61,
    TelegraphInterruptReward = 62,
    RestedReward = 63,
    UNUSED04 = 1,
    UNUSED03 = 2,
    LootArtifact = 3
}
function Spell:GetThresholdTime()
end
function Spell:GetRequiredLevel()
end
function Spell:IsSelfSpell()
end
function Spell:IsFreeformTarget()
end
function Spell:IsMovingInterrupted()
end
function Spell:IsBeneficial()
end
Spell.CodeEnumSpellClass = {
    BuffDispellable = 1,
    BuffNonDispellable = 2,
    DebuffDispellable = 3,
    DebuffNonDispellable = 4,
    BuffNonDispelRightClickOk = 1
}
Spell.CodeEnumCastResult = {
    Ok = 1,
    UnableToCreateSpell = 2,
    MovingToCast = 3,
    PendingSpellCast = 4,
    SpellUnkown = 39,
    SpellBad = 6,
    SpellCancelled = 7,
    SpellMaxChannel = 8,
    SpellRemoved = 9,
    SpellCountered = 10,
    SpellCastingInterrupts = 11,
    SpellInterrupted = 12,
    SpellCombatModeActiveCount = 13,
    SpellAlreadyCasting = 14,
    SpellGlobalCooldown = 15,
    SpellCooldown = 16,
    SpellGroupCooldown = 17,
    SpellPreRequisites = 18,
    ActionBarSetDisallows = 19,
    DamageInterrupts = 20,
    InvalidInventoryIndex = 21,
    ItemUnknown = 22,
    ItemBad = 23,
    ItemNoSpellId = 24,
    ItemUnEquipped = 25,
    ItemCharges = 26,
    ItemTooHighLevel = 27,
    ItemAchievmentComplete = 40,
    ItemQuestRequirementsNotMet = 29,
    ItemObjectiveComplete = 30,
    CasterUnknown = 31,
    CasterMustHaveTarget = 32,
    CasterCannotBePrimaryTarget = 33,
    CasterNotIncontrolOfSelf = 34,
    CasterMovement = 35,
    CasterMaxCast = 36,
    CCStun = 37,
    CCSleep = 38,
    CCRoot = 39,
    CCDisarm = 40,
    CCSilence = 41,
    CCPolymorph = 42,
    CCFear = 43,
    CCHold = 44,
    CasterVitalCostHealth = 45,
    CasterVitalCostXp = 46,
    CasterVitalCostMoney = 47,
    CasterVitalCostCurrency1 = 48,
    CasterVitalCostCurrency2 = 49,
    CasterVitalCostCurrency3 = 50,
    CasterVitalCostResource0 = 51,
    CasterVitalCostResource1 = 52,
    CasterVitalCostResource2 = 53,
    CasterVitalCostResource3 = 54,
    CasterVitalCostResource4 = 55,
    CasterVitalCostResource5 = 56,
    CasterVitalCostResource6 = 57,
    Caster_CannotBeDead = 58,
    Caster_MustBeDead = 59,
    Caster_CannotBeInCombatPVE = 41,
    Caster_MustBeInCombatPVE = 42,
    Caster_CannotBe_InCombatPVP = 43,
    Caster_MustBe_InCombatPVP = 44,
    Caster_CannotBe_Moving = 64,
    Caster_MustBe_Moving = 65,
    Caster_CannotBe_Stealth = 66,
    Caster_MustBe_Stealth = 67,
    Caster_CannotBe_Piloting = 68,
    Caster_MustBe_Piloting = 69,
    Caster_CannotBe_Embarked = 70,
    Caster_MustBe_Embarked = 71,
    Caster_CannotBe_Taxi = 72,
    Caster_MustBe_Taxi = 73,
    Caster_CannotBe_Stun = 74,
    Caster_MustBe_Stun = 75,
    Caster_CannotBe_Sleep = 76,
    Caster_MustBe_Sleep = 77,
    Caster_CannotBe_Root = 78,
    Caster_MustBe_Root = 79,
    Caster_CannotBe_Disarm = 80,
    Caster_MustBe_Disarm = 81,
    Caster_CannotBe_Silence = 82,
    Caster_MustBe_Silence = 83,
    Caster_CannotBe_Pacify = 84,
    Caster_MustBe_Pacify = 85,
    Caster_CannotBe_Fear = 86,
    Caster_MustBe_Fear = 87,
    Caster_CannotBe_Confuse = 88,
    Caster_MustBe_Confuse = 89,
    TargetGroup = 90,
    TargetUnknown = 91,
    NoTarget = 92,
    Target_ImmuneToSpellType = 93,
    Target_ImmuneToSpell = 94,
    Target_ImmuneToSpellGroupList = 95,
    Target_ImmuneToSpellGroup = 96,
    Target_Invulnerable = 97,
    TargetMaxTarget = 98,
    TargetVital = 99,
    TargetFaction = 100,
    TargetIsNotUseable = 101,
    TargetOrientation = 102,
    TargetCannotBePlayer = 103,
    TargetCannotBeNpc = 104,
    TargetRangeMin = 105,
    TargetRangeMax = 106,
    Target_CannotBeDead = 107,
    Target_MustBeDead = 108,
    Target_CannotBeInCombatPVE = 45,
    Target_MustBeInCombatPVE = 46,
    Target_CannotBe_InCombatPVP = 47,
    Target_MustBe_InCombatPVP = 48,
    Target_CannotBe_Moving = 113,
    Target_MustBe_Moving = 114,
    Target_CannotBe_Stealth = 115,
    Target_MustBe_Stealth = 116,
    Target_CannotBe_Piloting = 117,
    Target_MustBe_Piloting = 118,
    Target_CannotBe_Embarked = 119,
    Target_MustBe_Embarked = 120,
    Target_CannotBe_Taxi = 121,
    Target_MustBe_Taxi = 122,
    Target_CannotBe_Stun = 123,
    Target_MustBe_Stun = 124,
    Target_CannotBe_Sleep = 125,
    Target_MustBe_Sleep = 126,
    Target_CannotBe_Root = 127,
    Target_MustBe_Root = 128,
    Target_CannotBe_Disarm = 129,
    Target_MustBe_Disarm = 130,
    Target_CannotBe_Silence = 131,
    Target_MustBe_Silence = 132,
    Target_CannotBe_Pacify = 133,
    Target_MustBe_Pacify = 134,
    Target_CannotBe_Fear = 135,
    Target_MustBe_Fear = 136,
    Target_CannotBe_Confuse = 137,
    Target_MustBe_Confuse = 138,
    Target_CannotBe_Swimming = 139,
    Target_MustBe_Swimming = 140,
    InWrongWorldZone = 141,
    DuelOver = 142,
    UNUSED142 = 143,
    UNUSED143 = 144,
    MissingResult = 145,
    IsP2PTrading = 146,
    ClientSideInteractionFail = 147,
    StackingRefreshExistingSpell = 148,
    StackingTargetHasMorePowerfulSpells = 149,
    StackingCasterHasMorePowerfulSpells = 150,
    StackingError = 151,
    Prereq_CasterCast = 152,
    CCKnockdown = 153,
    CCVulnerability = 154,
    Target_MustBe_Knockdown = 155,
    Target_MustBe_Vulnerability = 156,
    Caster_MustBe_Vulnerability = 157,
    Caster_MustBe_Knockdown = 158,
    Caster_CannotBe_Knockdown = 159,
    Caster_CannotBe_Vulnerability = 160,
    Target_CannotBe_Vulnerability = 161,
    Target_CannotBe_Knockdown = 162,
    MissingReagent_Item = 163,
    MissingReagent_ItemFamily = 164,
    MissingReagent_ItemCategory = 165,
    MissingReagent_ItemType = 166,
    Caster_Needs_LoS = 167,
    CasterVitalCostMana = 168,
    TargetImmuneToSpellEffect = 169,
    WeaponSlot = 170,
    Caster_MustBe_Jumping = 171,
    Caster_CannotBe_Jumping = 172,
    Target_CannotBe_Jumping = 173,
    Target_MustBe_Jumping = 174,
    InvalidPosition = 175,
    CasterVitalCost = 176,
    CasterVitalCostShieldCapacity = 177,
    CasterVitalCostResource7 = 178,
    FailSpecialRestrictions = 179,
    NoValidActivateSpell = 180,
    SchematicAlreadyKnown = 181,
    TradeskillTier = 182,
    SpellNoCharges = 183,
    TargetRangeVertical = 184,
    StackingDuplicateDurationalSpell = 185,
    SpellMaxPhaseReached = 186,
    CCVulnerabilityWithAct = 187,
    CCDisorient = 188,
    CCDisable = 189,
    CCTaunt = 190,
    CCDeTaunt = 191,
    CCBlind = 192,
    CCKnockback = 193,
    CCPushback = 194,
    CCPull = 195,
    CCPositionSwitch = 196,
    CCTether = 197,
    CCSnare = 198,
    Caster_MustBe_Polymorph = 199,
    Target_MustBe_Polymorph = 200,
    Caster_CannotBe_Polymorph = 201,
    Target_CannotBe_Polymorph = 202,
    Caster_MustBe_Hold = 203,
    Target_MustBe_Hold = 204,
    Caster_CannotBe_Hold = 205,
    Target_CannotBe_Hold = 206,
    Caster_MustBe_Disorient = 207,
    Target_MustBe_Disorient = 208,
    Caster_CannotBe_Disorient = 209,
    Target_CannotBe_Disorient = 210,
    Caster_MustBe_Disable = 211,
    Target_MustBe_Disable = 212,
    Caster_CannotBe_Disable = 213,
    Target_CannotBe_Disable = 214,
    Caster_MustBe_Taunt = 215,
    Target_MustBe_Taunt = 216,
    Caster_CannotBe_Taunt = 217,
    Target_CannotBe_Taunt = 218,
    Caster_MustBe_DeTaunt = 219,
    Target_MustBe_DeTaunt = 220,
    Caster_CannotBe_DeTaunt = 221,
    Target_CannotBe_DeTaunt = 222,
    Caster_MustBe_Blind = 223,
    Target_MustBe_Blind = 224,
    Caster_CannotBe_Blind = 225,
    Target_CannotBe_Blind = 226,
    Caster_MustBe_Knockback = 227,
    Target_MustBe_Knockback = 228,
    Caster_CannotBe_Knockback = 229,
    Target_CannotBe_Knockback = 230,
    Caster_MustBe_Pushback = 231,
    Target_MustBe_Pushback = 232,
    Caster_CannotBe_Pushback = 233,
    Target_CannotBe_Pushback = 234,
    Caster_MustBe_Pull = 235,
    Target_MustBe_Pull = 236,
    Caster_CannotBe_Pull = 237,
    Target_CannotBe_Pull = 238,
    Caster_MustBe_PositionSwitch = 239,
    Target_MustBe_PositionSwitch = 240,
    Caster_CannotBe_PositionSwitch = 241,
    Target_CannotBe_PositionSwitch = 242,
    Caster_MustBe_Tether = 243,
    Target_MustBe_Tether = 244,
    Caster_CannotBe_Tether = 245,
    Target_CannotBe_Tether = 246,
    Caster_MustBe_Snare = 247,
    Target_MustBe_Snare = 248,
    Caster_CannotBe_Snare = 249,
    Target_CannotBe_Snare = 250,
    CasterVitalCostInterruptArmor = 251,
    CCNoAbilities = 252,
    Blacklisted = 253,
    TargetCannotBePickup = 254,
    CasterVitalCostAbsorption = 255,
    Target_MustBe_CastersPet = 256,
    Target_MustBe_CastersMaster = 257,
    CCInterrupt = 258,
    Caster_MustBe_Interrupt = 259,
    Target_MustBe_Interrupt = 260,
    Caster_CannotBe_Interrupt = 261,
    Target_CannotBe_Interrupt = 262,
    CSICooldown = 263,
    CCDaze = 264,
    Caster_MustBe_Daze = 265,
    Target_MustBe_Daze = 266,
    Caster_CannotBe_Daze = 267,
    Target_CannotBe_Daze = 268,
    CCSubdue = 269,
    Caster_MustBe_Subdue = 270,
    Target_MustBe_Subdue = 271,
    Caster_CannotBe_Subdue = 272,
    Target_CannotBe_Subdue = 273,
    Target_CannotBe_Evading = 274,
    Target_StructuredPlugBenefitRestricted = 275,
    CasterVitalCostPublicResource0 = 276,
    CasterVitalCostPublicResource1 = 277,
    CasterVitalCostPublicResource2 = 278,
    InactiveInnateAbilitySpell = 279,
    Caster_CannotBe_Swimming = 280,
    Caster_MustBe_Swimming = 281,
    Prereq_TargetCast = 282,
    Prereq_CasterPersistence = 283,
    Prereq_TargetPersistence = 284,
    Prereq_Trap = 285,
    IllegalSpellCast = 286,
    TargetNotInSameGroup = 287,
    BossToken_Permission = 288,
    BossToken_NotReady = 289,
    CCGrounded = 290,
    Caster_MustBe_Grounded = 291,
    Target_MustBe_Grounded = 292,
    Caster_CannotBe_Grounded = 293,
    Target_CannotBe_Grounded = 294,
    SpellUnknown = 1,
    ItemAchievementComplete = 2,
    Caster_CannotBeInCombat = 3,
    Caster_MustBeInCombat = 4,
    Target_CannotBeInCombat = 5,
    Target_MustBeInCombat = 6,
    CCDisableCinematic = 7,
    Caster_MustBe_DisableCinematic = 8,
    Target_MustBe_DisableCinematic = 9,
    Caster_CannotBe_DisableCinematic = 10,
    Target_CannotBe_DisableCinematic = 11,
    CCAbilityRestriction = 12,
    Caster_MustBe_AbilityRestriction = 13,
    Target_MustBe_AbilityRestriction = 14,
    Caster_CannotBe_AbilityRestriction = 15,
    Target_CannotBe_AbilityRestriction = 16,
    Target_VehicleBenefitRestricted = 17,
    TargetCannotBePet = 18,
    Target_HostileInvulnerability = 19,
    Target_InvulnerableToOther = 20,
    Target_BeneficialInvulnerability = 21,
    Caster_MustBe_Falling = 22,
    Caster_CannotBe_Falling = 23,
    Target_CannotBe_Falling = 24,
    Target_MustBe_Falling = 25,
    Caster_MustBe_Sprinting = 26,
    Caster_CannotBe_Sprinting = 27,
    Target_CannotBe_Sprinting = 28,
    Target_MustBe_Sprinting = 29,
    Queued = 30,
    ItemWrongRace = 31,
    ItemWrongClass = 32,
    ItemAlreadyUnlocked = 33,
    PlayerSpellPending = 34,
    Target_MustBe_PvpFlagged = 35,
    Caster_MustBe_PvpFlagged = 36,
    Target_OutsideTelegraph = 37,
    ShieldsOverloaded = 38
}
Spell.CodeEnumSpellEffectType = {
    UnitPropertyModifier = 1,
    VitalModifier = 2,
    SpellCounter = 3,
    ForcedMove = 4,
    CCStateSet = 5,
    Transference = 6,
    SummonVehicle = 7,
    Activate = 8,
    Damage = 9,
    FactionSet = 10,
    Heal = 11,
    Harvest = 12,
    DistanceDependentDamage = 13,
    Script = 14,
    Proc = 15,
    UnitStateSet = 16,
    Resurrect = 17,
    Fluff = 18,
    Scale = 19,
    ProxyLinearAE = 20,
    SummonCreature = 21,
    HousingTeleport = 22,
    ActionBarSet = 23,
    ForcedAction = 24,
    ProxyChannel = 25,
    Proxy = 26,
    CCStateBreak = 27,
    ForceFacing = 28,
    Absorption = 29,
    SapVital = 30,
    Disguise = 31,
    SpellImmunity = 32,
    DistributedDamage = 33,
    ChangePhase = 34,
    NpcExecutionDelay = 35,
    SummonMount = 36,
    ReputationModify = 37,
    GiveSchematic = 38,
    ModifySchematic = 39,
    TradeSkillProfession = 40,
    QuestAdvanceObjective = 41,
    GiveItemToPlayer = 42,
    GiveLootTableToPlayer = 43,
    NpcLootTableModify = 44,
    ThreatModification = 45,
    ThreatTransfer = 46,
    WarplotTeleport = 47,
    CraftItem = 48,
    ItemBreakdown = 49,
    SpellForceRemoveChanneled = 50,
    ModifyInterruptArmor = 51,
    SpellDispel = 52,
    TradeSkillProfessionXp = 53,
    ModifySpell = 54,
    ModifySpellEffect = 55,
    AddSpell = 56,
    AddSpellEffect = 57,
    SuppressSpellEffect = 58,
    CharmCreature = 20,
    NpcSetAIState = 21,
    VacuumLoot = 61,
    RecalculateSpellModifications = 22,
    ShieldOverload = 63,
    Teleport = 64,
    TitleGrant = 65,
    TitleRevoke = 66,
    VendorPriceModifier = 67,
    GrantCharmerPet = 23,
    RechargeItemBatteries = 69,
    FacilityModification = 70,
    PetAIStanceSet = 71,
    ModifySpellCooldown = 72,
    FinishingMove = 73,
    ChangeIcon = 74,
    ItemVisualSwap = 75,
    AggroImmune = 76,
    HobbyWrangleCreature = 24,
    SpellEffectImmunity = 78,
    SpellForceRemove = 79,
    RavelSignal = 80,
    ChangeDisplayName = 81,
    Stealth = 82,
    RemoveStealth = 83,
    PathActionExplorerDig = 84,
    HazardEnable = 85,
    HazardModify = 86,
    HazardSuspend = 87,
    NpcForceFacing = 88,
    DEPRECATED01 = 25,
    DEPRECATED02 = 26,
    AchievementAdvance = 91,
    PathXpModify = 92,
    ProxyChannelVariableTime = 93,
    FullScreenEffect = 94,
    ProxyRandomExclusive = 95,
    DespawnUnit = 96,
    SummonPet = 97,
    MimicDisplayName = 98,
    MimicDisguise = 99,
    GrantXP = 100,
    DatacubeUpdate = 101,
    DatacubeVolumeUpdate = 102,
    SettlerCampfire = 103,
    SummonTrap = 104,
    SetBusy = 105,
    CooldownReset = 106,
    RestedXpDecorBonus = 107,
    LearnDyeColor = 108,
    PetCastSpell = 109,
    DisguiseOutfit = 110,
    RewardBuffModifier = 111,
    HousingEscape = 112,
    NPCForceAIMovement = 113,
    HealShields = 114,
    PathMissionIncrement = 115,
    GrantLevelScaledXP = 116,
    DelayDeath = 117,
    GrantLevelScaledPrestige = 118,
    UnlockPetFlair = 119,
    WarplotPlugUpgrade = 120,
    SetMatchingEligibility = 121,
    UnlockActionBar = 1,
    UNUSED040 = 2,
    ModifyCreatureFlags = 3,
    UNUSED061 = 4,
    UNUSED063 = 5,
    ApplyLASChanges = 6,
    GiveAbilityPointsToPlayer = 7,
    ModifyAbilityCharges = 8,
    UNUSED091 = 9,
    UNUSED104 = 10,
    UnlockMount = 11,
    UnlockInlaidAugment = 12,
    GiveAugmentPowerToPlayer = 13,
    TemporarilyUnflagPvp = 14,
    SupportStuck = 15,
    MiniMapIcon = 16,
    Disembark = 17,
    ChangePlane = 18,
    ModifyRestedXP = 19
}
function Spell:GetBaseSpellId()
end
function Spell:GetCastTimeOverride()
end
function Spell:GetCastInfoString()
end
function Spell:GetProxyChannelData()
end
function Spell:GetCooldownRemaining()
end
function Spell:GetLasTierDesc()
end
function Spell:GetLasBonusEachTierDesc()
end
function Spell:GetGCDTime()
end
function Spell:__eq()
end
function Spell:__gc()
end
Spell.CodeEnumSpellTag = {
    Assault = 1,
    Support = 2,
    Path = 3,
    Misc = 4,
    Mount = 5,
    DoesNotUseSpecIndex = 6,
    Utility = 7,
    NotAutoActivated = 8
}

return Spell