local Spell = { }
Spell.__index = Spell

function Spell:GetAOETargetInfo()
end
function Spell:GetCastMethod()
end
function Spell:GetCastTime()
end
function Spell:GetCasterInnateRequirements()
end
function Spell:GetCasterInnateCosts()
end
function Spell:GetChannelData()
end
function Spell:GetClass()
end
function Spell:GetCombatMode()
end
function Spell:GetCooldownTime()
end
function Spell:GetFlavor()
end
function Spell:GetIcon()
end
function Spell:GetInstanceMaxCount()
end
function Spell:GetMaximumRange()
end
function Spell:GetMinimumRange()
end
function Spell:GetName()
end
function Spell:GetClassPower()
end
function Spell:GetPrerequisites()
end
function Spell:GetPrice()
end
function Spell:GetReagents()
end
function Spell:GetRequiredWorldZone()
end
function Spell:GetSchool()
end
function Spell:GetTargetAngle()
end
function Spell:GetTargetInnateRequirements()
end
function Spell:GetTier()
end
function Spell:IsNew()
end
function Spell:SetNewFlag(bNew)
end
function Spell:GetTradeskillRequirements()
end
function Spell.ShortcutCast()
end
function Spell.is()
end
function Spell.ShowFloater()
end
Spell.CodeEnumReagentType = {
  Item = 0,
  ItemFamily = 1,
  ItemCategory = 2
}
Spell.CodeEnumCastMethod = {
  Aura = 10,
  Channeled = 1,
  ChanneledField = 3,
  ChargeRelease = 7,
  ClientSideInteraction = 5,
  Multiphase = 8,
  Normal = 0,
  PressHold = 2,
  RapidTap = 6,
  Transactional = 9,
  UNUSED04 = 4
}
Spell.CodeEnumSchool = {
  Spell = 0,
  Melee = 1,
  Ranged = 2,
  Unarmed = 3
}
Spell.CodeEnumComparison = {
  Equals = 0,
  Greater = 1,
  GreaterThanEqualTo = 2,
  Less = 3,
  LessThanEqualTo = 4,
  Percent_Equals = 5,
  Percent_Greater = 6,
  Percent_GreaterThanEqualTo = 7,
  Percent_Less = 8,
  Percent_LessThanEqualTo = 9
}
Spell.CodeEnumAOESelectionType = {
  None = 0,
  Closest = 1,
  Furthest = 2,
  Random = 3,
  LowestAbsoluteHealth = 4,
  MissingMostHealth = 5
}
function Spell:GetId()
end
function Spell:GetAbilityCharges()
end
Spell.CombatMessageType = {
  Absorption_Done = 44,
  Absorption_Taken = 43,
  Achievement = 39,
  Combat_Block_Done = 13,
  Combat_Block_Taken = 12,
  Combat_Damage_Done = 4,
  Combat_Damage_Done_Critical = 5,
  Combat_Damage_Taken = 6,
  Combat_Damage_Taken_Critical = 7,
  Combat_Death = 23,
  Combat_Dodge_Done = 17,
  Combat_Dodge_Taken = 16,
  Combat_Falling_Damage_Done = 22,
  Combat_Healing_Done = 8,
  Combat_Healing_Done_Critical = 9,
  Combat_Healing_Taken = 10,
  Combat_Healing_Taken_Critical = 11,
  Combat_NoEffect_Done = 19,
  Combat_NoEffect_Taken = 18,
  Combat_Parry_Done = 15,
  Combat_Parry_Taken = 14,
  Combat_Shallow_Done = 21,
  Combat_Shallow_Taken = 20,
  Error = 24,
  Experience = 1,
  Experience_ClusterBonus = 41,
  Experience_KillCreature = 40,
  Experience_Quest = 42,
  Faction = 28,
  General = 0,
  KillingSpreeReward = 58,
  KillPerformanceReward = 56,
  LocationChange = 3,
  LootArtifact = 36,
  LootAverage = 30,
  LootBase = 29,
  LootExcellent = 32,
  LootGood = 31,
  LootInferior = 59,
  LootLegendary = 37,
  LootQuestActivation = 38,
  LootSuperb = 33,
  MultiKillReward = 57,
  PlayerPath = 55,
  QuestUpdate = 2,
  RestedReward = 62,
  Special_Done = 52,
  Special_Taken = 53,
  SpellFailure = 25,
  SpellFailure_Long = 47,
  SpellFailure_Medium = 48,
  SpellFailure_Short = 49,
  SpellFailure_Target_Feet = 51,
  SpellFailure_Target_Head = 50,
  TelegraphEvadeReward = 60,
  TelegraphInterruptReward = 61,
  Transference_Done = 46,
  Transference_Taken = 45,
  UNUSED00 = 26,
  UNUSED01 = 27,
  UNUSED02 = 54,
  UNUSED03 = 35,
  UNUSED04 = 34
}
function Spell:GetThresholdTime()
end
function Spell:GetRequiredLevel()
end
function Spell:IsSelfSpell()
end
function Spell:IsFreeformTarget()
end
function Spell:IsMovingInterrupted()
end
function Spell:IsBeneficial()
end
Spell.CodeEnumSpellClass = {
  BuffDispellable = 36,
  BuffNonDispellable = 37,
  BuffNonDispelRightClickOk = 14,
  DebuffDispellable = 38,
  DebuffNonDispellable = 39
}
Spell.CodeEnumCastResult = {
  ActionBarSetDisallows = 18,
  Blacklisted = 252,
  BossToken_NotReady = 288,
  BossToken_Permission = 287,
  Caster_CannotBe_AbilityRestriction = 302,
  Caster_CannotBe_Blind = 224,
  Caster_CannotBe_Confuse = 87,
  Caster_CannotBe_Daze = 266,
  Caster_CannotBe_DeTaunt = 220,
  Caster_CannotBe_Disable = 212,
  Caster_CannotBe_DisableCinematic = 297,
  Caster_CannotBe_Disarm = 79,
  Caster_CannotBe_Disorient = 208,
  Caster_CannotBe_Embarked = 69,
  Caster_CannotBe_Falling = 310,
  Caster_CannotBe_Fear = 85,
  Caster_CannotBe_Grounded = 292,
  Caster_CannotBe_Hold = 204,
  Caster_CannotBe_Interrupt = 260,
  Caster_CannotBe_Jumping = 171,
  Caster_CannotBe_Knockback = 228,
  Caster_CannotBe_Knockdown = 158,
  Caster_CannotBe_Moving = 63,
  Caster_CannotBe_Pacify = 83,
  Caster_CannotBe_Piloting = 67,
  Caster_CannotBe_Polymorph = 200,
  Caster_CannotBe_PositionSwitch = 240,
  Caster_CannotBe_Pull = 236,
  Caster_CannotBe_Pushback = 232,
  Caster_CannotBe_Root = 77,
  Caster_CannotBe_Silence = 81,
  Caster_CannotBe_Sleep = 75,
  Caster_CannotBe_Snare = 248,
  Caster_CannotBe_Sprinting = 314,
  Caster_CannotBe_Stealth = 65,
  Caster_CannotBe_Stun = 73,
  Caster_CannotBe_Subdue = 271,
  Caster_CannotBe_Swimming = 279,
  Caster_CannotBe_Taunt = 216,
  Caster_CannotBe_Taxi = 71,
  Caster_CannotBe_Tether = 244,
  Caster_CannotBe_Vulnerability = 159,
  Caster_CannotBeDead = 57,
  Caster_CannotBeInCombat = 59,
  Caster_MustBe_AbilityRestriction = 300,
  Caster_MustBe_Blind = 222,
  Caster_MustBe_Confuse = 88,
  Caster_MustBe_Daze = 264,
  Caster_MustBe_DeTaunt = 218,
  Caster_MustBe_Disable = 210,
  Caster_MustBe_DisableCinematic = 295,
  Caster_MustBe_Disarm = 80,
  Caster_MustBe_Disorient = 206,
  Caster_MustBe_Embarked = 70,
  Caster_MustBe_Falling = 309,
  Caster_MustBe_Fear = 86,
  Caster_MustBe_Grounded = 290,
  Caster_MustBe_Hold = 202,
  Caster_MustBe_Interrupt = 258,
  Caster_MustBe_Jumping = 170,
  Caster_MustBe_Knockback = 226,
  Caster_MustBe_Knockdown = 157,
  Caster_MustBe_Moving = 64,
  Caster_MustBe_Pacify = 84,
  Caster_MustBe_Piloting = 68,
  Caster_MustBe_Polymorph = 198,
  Caster_MustBe_PositionSwitch = 238,
  Caster_MustBe_Pull = 234,
  Caster_MustBe_Pushback = 230,
  Caster_MustBe_PvpFlagged = 323,
  Caster_MustBe_Root = 78,
  Caster_MustBe_Silence = 82,
  Caster_MustBe_Sleep = 76,
  Caster_MustBe_Snare = 246,
  Caster_MustBe_Sprinting = 313,
  Caster_MustBe_Stealth = 66,
  Caster_MustBe_Stun = 74,
  Caster_MustBe_Subdue = 269,
  Caster_MustBe_Swimming = 280,
  Caster_MustBe_Taunt = 214,
  Caster_MustBe_Taxi = 72,
  Caster_MustBe_Tether = 242,
  Caster_MustBe_Vulnerability = 156,
  Caster_MustBeDead = 58,
  Caster_MustBeInCombat = 60,
  Caster_Needs_LoS = 166,
  CasterCannotBePrimaryTarget = 32,
  CasterMaxCast = 35,
  CasterMovement = 34,
  CasterMustHaveTarget = 31,
  CasterNotIncontrolOfSelf = 33,
  CasterUnknown = 30,
  CasterVitalCost = 175,
  CasterVitalCostAbsorption = 254,
  CasterVitalCostCurrency1 = 47,
  CasterVitalCostCurrency2 = 48,
  CasterVitalCostCurrency3 = 49,
  CasterVitalCostHealth = 44,
  CasterVitalCostInterruptArmor = 250,
  CasterVitalCostMana = 167,
  CasterVitalCostMoney = 46,
  CasterVitalCostPublicResource0 = 275,
  CasterVitalCostPublicResource1 = 276,
  CasterVitalCostPublicResource2 = 277,
  CasterVitalCostResource0 = 50,
  CasterVitalCostResource1 = 51,
  CasterVitalCostResource2 = 52,
  CasterVitalCostResource3 = 53,
  CasterVitalCostResource4 = 54,
  CasterVitalCostResource5 = 55,
  CasterVitalCostResource6 = 56,
  CasterVitalCostResource7 = 177,
  CasterVitalCostShieldCapacity = 176,
  CasterVitalCostXp = 45,
  CCAbilityRestriction = 299,
  CCBlind = 191,
  CCDaze = 263,
  CCDeTaunt = 190,
  CCDisable = 188,
  CCDisableCinematic = 294,
  CCDisarm = 39,
  CCDisorient = 187,
  CCFear = 42,
  CCGrounded = 289,
  CCHold = 43,
  CCInterrupt = 257,
  CCKnockback = 192,
  CCKnockdown = 152,
  CCNoAbilities = 251,
  CCPolymorph = 41,
  CCPositionSwitch = 195,
  CCPull = 194,
  CCPushback = 193,
  CCRoot = 38,
  CCSilence = 40,
  CCSleep = 37,
  CCSnare = 197,
  CCStun = 36,
  CCSubdue = 268,
  CCTaunt = 189,
  CCTether = 196,
  CCVulnerability = 153,
  CCVulnerabilityWithAct = 186,
  ClientSideInteractionFail = 146,
  CSICooldown = 262,
  DamageInterrupts = 19,
  DuelOver = 141,
  FailSpecialRestrictions = 178,
  IllegalSpellCast = 285,
  InactiveInnateAbilitySpell = 278,
  InvalidInventoryIndex = 20,
  InvalidPosition = 174,
  InWrongWorldZone = 140,
  IsP2PTrading = 145,
  ItemAchievementComplete = 27,
  ItemAlreadyUnlocked = 320,
  ItemBad = 22,
  ItemCharges = 25,
  ItemNoSpellId = 23,
  ItemObjectiveComplete = 29,
  ItemQuestRequirementsNotMet = 28,
  ItemTooHighLevel = 26,
  ItemUnEquipped = 24,
  ItemUnknown = 21,
  ItemWrongClass = 319,
  ItemWrongRace = 318,
  MissingReagent_Item = 162,
  MissingReagent_ItemCategory = 164,
  MissingReagent_ItemFamily = 163,
  MissingReagent_ItemType = 165,
  MissingResult = 144,
  MovingToCast = 2,
  NoTarget = 91,
  NoValidActivateSpell = 179,
  Ok = 0,
  PendingSpellCast = 3,
  PlayerSpellPending = 321,
  Prereq_CasterCast = 151,
  Prereq_CasterPersistence = 282,
  Prereq_TargetCast = 281,
  Prereq_TargetPersistence = 283,
  Prereq_Trap = 284,
  Queued = 317,
  SchematicAlreadyKnown = 180,
  ShieldsOverloaded = 326,
  SpellAlreadyCasting = 13,
  SpellBad = 5,
  SpellCancelled = 6,
  SpellCastingInterrupts = 10,
  SpellCombatModeActiveCount = 12,
  SpellCooldown = 15,
  SpellCountered = 9,
  SpellGlobalCooldown = 14,
  SpellGroupCooldown = 16,
  SpellInterrupted = 11,
  SpellMaxChannel = 7,
  SpellMaxPhaseReached = 185,
  SpellNoCharges = 182,
  SpellPreRequisites = 17,
  SpellRemoved = 8,
  SpellUnknown = 4,
  StackingCasterHasMorePowerfulSpells = 149,
  StackingDuplicateDurationalSpell = 184,
  StackingError = 150,
  StackingRefreshExistingSpell = 147,
  StackingTargetHasMorePowerfulSpells = 148,
  Target_BeneficialInvulnerability = 308,
  Target_CannotBe_AbilityRestriction = 303,
  Target_CannotBe_Blind = 225,
  Target_CannotBe_Confuse = 136,
  Target_CannotBe_Daze = 267,
  Target_CannotBe_DeTaunt = 221,
  Target_CannotBe_Disable = 213,
  Target_CannotBe_DisableCinematic = 298,
  Target_CannotBe_Disarm = 128,
  Target_CannotBe_Disorient = 209,
  Target_CannotBe_Embarked = 118,
  Target_CannotBe_Evading = 273,
  Target_CannotBe_Falling = 311,
  Target_CannotBe_Fear = 134,
  Target_CannotBe_Grounded = 293,
  Target_CannotBe_Hold = 205,
  Target_CannotBe_Interrupt = 261,
  Target_CannotBe_Jumping = 172,
  Target_CannotBe_Knockback = 229,
  Target_CannotBe_Knockdown = 161,
  Target_CannotBe_Moving = 112,
  Target_CannotBe_Pacify = 132,
  Target_CannotBe_Piloting = 116,
  Target_CannotBe_Polymorph = 201,
  Target_CannotBe_PositionSwitch = 241,
  Target_CannotBe_Pull = 237,
  Target_CannotBe_Pushback = 233,
  Target_CannotBe_Root = 126,
  Target_CannotBe_Silence = 130,
  Target_CannotBe_Sleep = 124,
  Target_CannotBe_Snare = 249,
  Target_CannotBe_Sprinting = 315,
  Target_CannotBe_Stealth = 114,
  Target_CannotBe_Stun = 122,
  Target_CannotBe_Subdue = 272,
  Target_CannotBe_Swimming = 138,
  Target_CannotBe_Taunt = 217,
  Target_CannotBe_Taxi = 120,
  Target_CannotBe_Tether = 245,
  Target_CannotBe_Vulnerability = 160,
  Target_CannotBeDead = 106,
  Target_CannotBeInCombat = 108,
  Target_HostileInvulnerability = 306,
  Target_ImmuneToSpell = 93,
  Target_ImmuneToSpellGroup = 95,
  Target_ImmuneToSpellGroupList = 94,
  Target_ImmuneToSpellType = 92,
  Target_Invulnerable = 96,
  Target_InvulnerableToOther = 307,
  Target_MustBe_AbilityRestriction = 301,
  Target_MustBe_Blind = 223,
  Target_MustBe_CastersMaster = 256,
  Target_MustBe_CastersPet = 255,
  Target_MustBe_Confuse = 137,
  Target_MustBe_Daze = 265,
  Target_MustBe_DeTaunt = 219,
  Target_MustBe_Disable = 211,
  Target_MustBe_DisableCinematic = 296,
  Target_MustBe_Disarm = 129,
  Target_MustBe_Disorient = 207,
  Target_MustBe_Embarked = 119,
  Target_MustBe_Falling = 312,
  Target_MustBe_Fear = 135,
  Target_MustBe_Grounded = 291,
  Target_MustBe_Hold = 203,
  Target_MustBe_Interrupt = 259,
  Target_MustBe_Jumping = 173,
  Target_MustBe_Knockback = 227,
  Target_MustBe_Knockdown = 154,
  Target_MustBe_Moving = 113,
  Target_MustBe_Pacify = 133,
  Target_MustBe_Piloting = 117,
  Target_MustBe_Polymorph = 199,
  Target_MustBe_PositionSwitch = 239,
  Target_MustBe_Pull = 235,
  Target_MustBe_Pushback = 231,
  Target_MustBe_PvpFlagged = 322,
  Target_MustBe_Root = 127,
  Target_MustBe_Silence = 131,
  Target_MustBe_Sleep = 125,
  Target_MustBe_Snare = 247,
  Target_MustBe_Sprinting = 316,
  Target_MustBe_Stealth = 115,
  Target_MustBe_Stun = 123,
  Target_MustBe_Subdue = 270,
  Target_MustBe_Swimming = 139,
  Target_MustBe_Taunt = 215,
  Target_MustBe_Taxi = 121,
  Target_MustBe_Tether = 243,
  Target_MustBe_Vulnerability = 155,
  Target_MustBeDead = 107,
  Target_MustBeInCombat = 109,
  Target_OutsideTelegraph = 325,
  Target_StructuredPlugBenefitRestricted = 274,
  Target_VehicleBenefitRestricted = 304,
  TargetCannotBeNpc = 103,
  TargetCannotBePet = 305,
  TargetCannotBePickup = 253,
  TargetCannotBePlayer = 102,
  TargetFaction = 99,
  TargetGroup = 89,
  TargetImmuneToSpellEffect = 168,
  TargetIsNotUseable = 100,
  TargetMaxTarget = 97,
  TargetNotInSameGroup = 286,
  TargetOrientation = 101,
  TargetRangeMax = 105,
  TargetRangeMin = 104,
  TargetRangeVertical = 183,
  TargetUnknown = 90,
  TargetVital = 98,
  TradeskillTier = 181,
  UnableToCreateSpell = 1,
  UNUSED142 = 142,
  UNUSED143 = 143,
  WeaponSlot = 169
}
Spell.CodeEnumSpellEffectType = {
  Absorption = 29,
  AchievementAdvance = 92,
  ActionBarSet = 23,
  Activate = 7,
  AddSpell = 57,
  AddSpellEffect = 58,
  AggroImmune = 77,
  ApplyLASChanges = 69,
  CCStateBreak = 27,
  CCStateSet = 4,
  ChangeDisplayName = 82,
  ChangeIcon = 75,
  ChangePhase = 34,
  ChangePlane = 133,
  CooldownReset = 108,
  CraftItem = 49,
  Damage = 8,
  DatacubeUpdate = 102,
  DatacubeVolumeUpdate = 103,
  DelayDeath = 121,
  DespawnUnit = 97,
  Disembark = 132,
  Disguise = 31,
  DisguiseOutfit = 112,
  DistanceDependentDamage = 12,
  DistributedDamage = 33,
  FacilityModification = 71,
  FactionSet = 9,
  FinishingMove = 74,
  Fluff = 17,
  ForcedAction = 24,
  ForcedMove = 3,
  ForceFacing = 28,
  FullScreenEffect = 95,
  GiveAbilityPointsToPlayer = 78,
  GiveAugmentPowerToPlayer = 128,
  GiveItemToPlayer = 43,
  GiveLootTableToPlayer = 44,
  GiveSchematic = 38,
  GrantLevelScaledPrestige = 122,
  GrantLevelScaledXP = 120,
  GrantXP = 101,
  Harvest = 11,
  HazardEnable = 86,
  HazardModify = 87,
  HazardSuspend = 88,
  Heal = 10,
  HealShields = 118,
  HousingEscape = 116,
  HousingTeleport = 22,
  ItemBreakdown = 50,
  ItemVisualSwap = 76,
  LearnDyeColor = 110,
  MimicDisguise = 100,
  MimicDisplayName = 99,
  MiniMapIcon = 131,
  ModifyAbilityCharges = 90,
  ModifyCreatureFlags = 60,
  ModifyInterruptArmor = 52,
  ModifyRestedXP = 134,
  ModifySchematic = 39,
  ModifySpell = 55,
  ModifySpellCooldown = 73,
  ModifySpellEffect = 56,
  NpcExecutionDelay = 35,
  NPCForceAIMovement = 117,
  NpcForceFacing = 89,
  NpcLootTableModify = 45,
  PathActionExplorerDig = 85,
  PathMissionIncrement = 119,
  PathXpModify = 93,
  PetAIStanceSet = 72,
  PetCastSpell = 111,
  Proc = 14,
  Proxy = 26,
  ProxyChannel = 25,
  ProxyChannelVariableTime = 94,
  ProxyLinearAE = 19,
  ProxyRandomExclusive = 96,
  QuestAdvanceObjective = 42,
  RavelSignal = 81,
  RechargeItemBatteries = 70,
  RemoveStealth = 84,
  ReputationModify = 37,
  RestedXpDecorBonus = 109,
  Resurrect = 16,
  RewardBuffModifier = 113,
  SapVital = 30,
  Scale = 18,
  Script = 13,
  SetBusy = 107,
  SetMatchingEligibility = 126,
  SettlerCampfire = 105,
  ShieldOverload = 64,
  SpellCounter = 2,
  SpellDispel = 53,
  SpellEffectImmunity = 79,
  SpellForceRemove = 80,
  SpellForceRemoveChanneled = 51,
  SpellImmunity = 32,
  Stealth = 83,
  SummonCreature = 21,
  SummonMount = 36,
  SummonPet = 98,
  SummonTrap = 106,
  SummonVehicle = 6,
  SupportStuck = 130,
  SuppressSpellEffect = 59,
  Teleport = 65,
  TemporarilyUnflagPvp = 129,
  ThreatModification = 46,
  ThreatTransfer = 47,
  TitleGrant = 66,
  TitleRevoke = 67,
  TradeSkillProfession = 41,
  TradeSkillProfessionXp = 54,
  Transference = 5,
  UnitPropertyModifier = 0,
  UnitStateSet = 15,
  UnlockActionBar = 20,
  UnlockInlaidAugment = 127,
  UnlockMount = 125,
  UnlockPetFlair = 123,
  UNUSED040 = 40,
  UNUSED061 = 61,
  UNUSED063 = 63,
  UNUSED091 = 91,
  UNUSED104 = 104,
  VacuumLoot = 62,
  VendorPriceModifier = 68,
  VitalModifier = 1,
  WarplotPlugUpgrade = 124,
  WarplotTeleport = 48
}
function Spell:GetBaseSpellId()
end
function Spell:GetCastTimeOverride()
end
function Spell:GetCastInfoString()
end
function Spell:GetProxyChannelData()
end
function Spell:GetCooldownRemaining()
end
function Spell:GetLasTierDesc()
end
function Spell:GetLasBonusEachTierDesc()
end
function Spell:GetGCDTime()
end
function Spell:__eq()
end
function Spell:__gc()
end
Spell.CodeEnumSpellTag = {
  Assault = 1,
  Support = 2,
  Path = 3,
  Misc = 4,
  Mount = 5,
  DoesNotUseSpecIndex = 6,
  Utility = 7,
  NotAutoActivated = 8
}

return Spell